### ISSUE TITLE
Simplify Docker Deployment

### ISSUE THREAD

**Issue by ulgens** [onurgu/turkish-parliament-texts#2]

**Comment by sahinbatmaz** [comment]
Merhaba, 
Su an birkac bash scripti ile deployment yapiliyor. Hangi açılardan nasil bir sadelestirme guzel olur?

**Comment by ulgens** [comment]
Şöyle ki

```
bash ./setup/docker/0_bower.sh
bash ./setup/docker/1_volume.sh
bash ./setup/docker/2_postgres.sh
bash ./setup/docker/3_django.sh
```

şeklinde bir kurulum adımı mevcut. Normalde bu adımlar, ihtiyaca göre `docker build` veya `docker-compose build`le yönetilen şeyler. Art arda bir kaç farklı betik çağırmak ve `x değiştiğinde y'yi çalıştır` gibi direktifler uygulamak yerine ortamı hazırlamak için `build`, çalıştırmak için `up` komutlarının yeterli olduğu bir akış mümkün.

Bunun dışında, `docker/` klasörü altındaki `init`, `run` ve `x_y.sh` bölümlemesinin biraz daha temiz şekilde yapılabileceğini düşünüyorum. İsterseniz aklımdan geçeni detaylı paylaşabilirim, veya direkt bir PR üzerinden yürüyebiliriz.
